# Generated by Django 6.0.6 on 2026-06-15 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0008_promote_org_admins_to_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('teacher', 'معلم'), ('organization', 'سازمان')], db_index=True, max_length=16)),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(db_index=True, max_length=15, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('expertise', models.CharField(blank=True, max_length=255, verbose_name='حوزه تدریس / تخصص')),
                ('org_name', models.CharField(blank=True, max_length=255, verbose_name='نام سازمان')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='شهر')),
                ('expected_students', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد تقریبی دانش\u200cآموز')),
                ('website', models.URLField(blank=True, verbose_name='وب\u200cسایت')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات متقاضی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('contacted', 'تماس گرفته شد'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], db_index=True, default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت داخلی')),
                ('reject_reason', models.CharField(blank=True, max_length=255)),
                ('registration_token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('token_consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.organization')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست دسترسی',
                'verbose_name_plural': 'درخواست\u200cهای دسترسی',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'status'], name='waitlist_ac_kind_a6b5cc_idx')],
            },
        ),
    ]
