# Generated by Django 6.0.6 on 2026-08-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role_advisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='grade',
            field=models.CharField(blank=True, choices=[('01', 'پایه اول'), ('02', 'پایه دوم'), ('03', 'پایه سوم'), ('04', 'پایه چهارم'), ('05', 'پایه پنجم'), ('06', 'پایه ششم'), ('07', 'هفتم'), ('08', 'هشتم'), ('09', 'نهم'), ('10', 'دهم'), ('11', 'یازدهم'), ('12', 'دوازدهم')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='major',
            field=models.CharField(blank=True, choices=[('math', 'ریاضی فیزیک'), ('science', 'علوم تجربی'), ('humanities', 'علوم انسانی'), ('theology', 'علوم و معارف اسلامی'), ('technical', 'فنی و حرفه\u200cای و کاردانش')], max_length=20, null=True),
        ),
    ]
