# Generated by Django 6.0 on 2026-02-02 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminnotification',
            new_name='notificatio_audienc_ace085_idx',
            old_name='notificatio_audience_0fd38e_idx',
        ),
    ]
