# Generated by Django 6.0 on 2026-01-05 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_add_structure_step2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classcreationsession',
            name='client_request_id',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name='classcreationsession',
            constraint=models.UniqueConstraint(fields=('teacher', 'client_request_id'), name='uniq_class_creation_teacher_client_request_id'),
        ),
    ]
