# Generated by GitHub Copilot

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classcreationsession_client_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcreationsession',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classcreationsession',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClassInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32)),
                ('invite_code', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='invites',
                        to='classes.classcreationsession',
                    ),
                ),
            ],
            options={},
        ),
        migrations.AddConstraint(
            model_name='classinvitation',
            constraint=models.UniqueConstraint(fields=('session', 'phone'), name='uniq_class_invite_session_phone'),
        ),
        migrations.AddConstraint(
            model_name='classinvitation',
            constraint=models.UniqueConstraint(fields=('session', 'invite_code'), name='uniq_class_invite_session_code'),
        ),
    ]
