# Generated by Django 6.0 on 2026-01-07 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_classcreationsession_level_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(blank=True, default='', max_length=64)),
                ('thread_key', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_chat_threads', to='classes.classcreationsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_course_chat_threads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourseChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=16)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('widget', 'Widget')], max_length=16)),
                ('content', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('lesson_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='classes.studentcoursechatthread')),
            ],
        ),
        migrations.AddConstraint(
            model_name='studentcoursechatthread',
            constraint=models.UniqueConstraint(fields=('session', 'student', 'lesson_id'), name='uniq_student_course_chat_thread_session_student_lesson'),
        ),
        migrations.AddIndex(
            model_name='studentcoursechatmessage',
            index=models.Index(fields=['thread', 'created_at'], name='classes_stu_thread__24c750_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcoursechatmessage',
            index=models.Index(fields=['lesson_id', 'created_at'], name='classes_stu_lesson__a8d4c0_idx'),
        ),
    ]
