# Generated by Django 6.0 on 2026-01-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_studentcoursechatthread_studentcoursechatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcreationsession',
            name='exam_prep_json',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='classcreationsession',
            name='pipeline_type',
            field=models.CharField(choices=[('class', 'Class Pipeline'), ('exam_prep', 'Exam Prep Pipeline')], default='class', max_length=16),
        ),
        migrations.AlterField(
            model_name='classcreationsession',
            name='status',
            field=models.CharField(choices=[('transcribing', 'Transcribing'), ('transcribed', 'Transcribed'), ('structuring', 'Structuring'), ('structured', 'Structured'), ('prereq_extracting', 'Prerequisites: Extracting'), ('prereq_extracted', 'Prerequisites: Extracted'), ('prereq_teaching', 'Prerequisites: Teaching'), ('prereq_taught', 'Prerequisites: Taught'), ('recapping', 'Recap: Generating'), ('recapped', 'Recap: Ready'), ('exam_transcribing', 'Exam Prep: Transcribing'), ('exam_transcribed', 'Exam Prep: Transcribed'), ('exam_structuring', 'Exam Prep: Extracting Q&A'), ('exam_structured', 'Exam Prep: Ready'), ('failed', 'Failed')], default='transcribing', max_length=32),
        ),
    ]
