# Generated by Django 6.0 on 2026-02-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0016_classannouncement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classannouncement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
