# Generated by Django 6.0.2 on 2026-02-10 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0017_alter_classannouncement_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcreationsession',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='classcreationsession',
            name='pipeline_type',
            field=models.CharField(choices=[('class', 'Class Pipeline'), ('exam_prep', 'Exam Prep Pipeline')], db_index=True, default='class', max_length=16),
        ),
        migrations.AlterField(
            model_name='classcreationsession',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='classcreationsession',
            name='status',
            field=models.CharField(choices=[('transcribing', 'Transcribing'), ('transcribed', 'Transcribed'), ('structuring', 'Structuring'), ('structured', 'Structured'), ('prereq_extracting', 'Prerequisites: Extracting'), ('prereq_extracted', 'Prerequisites: Extracted'), ('prereq_teaching', 'Prerequisites: Teaching'), ('prereq_taught', 'Prerequisites: Taught'), ('recapping', 'Recap: Generating'), ('recapped', 'Recap: Ready'), ('exam_transcribing', 'Exam Prep: Transcribing'), ('exam_transcribed', 'Exam Prep: Transcribed'), ('exam_structuring', 'Exam Prep: Extracting Q&A'), ('exam_structured', 'Exam Prep: Ready'), ('failed', 'Failed')], db_index=True, default='transcribing', max_length=32),
        ),
        migrations.AlterField(
            model_name='classinvitation',
            name='invite_code',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='classinvitation',
            name='phone',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='classcreationsession',
            index=models.Index(fields=['is_published', 'pipeline_type', '-published_at'], name='idx_session_pub_type_pubat'),
        ),
    ]
