# Generated by Django 6.0.2 on 2026-02-21 22:28

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0018_alter_classcreationsession_is_published_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name='classes_classcreationsession' AND column_name='organization_id'
                ) THEN
                    ALTER TABLE "classes_classcreationsession" ADD COLUMN "organization_id" bigint NULL;
                    ALTER TABLE "classes_classcreationsession" ADD CONSTRAINT "classes_classcreations_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "organizations_organization"("id") DEFERRABLE INITIALLY DEFERRED;
                    CREATE INDEX "classes_classcreationsession_organization_id_idx" ON "classes_classcreationsession" ("organization_id");
                END IF;
            END
            $$;
            """,
            reverse_sql="""
            ALTER TABLE "classes_classcreationsession" DROP COLUMN IF EXISTS "organization_id";
            """,
            state_operations=[
                migrations.AddField(
                    model_name='classcreationsession',
                    name='organization',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='organizations.organization', verbose_name='سازمان'),
                ),
            ]
        ),
    ]
