# Generated by Django 6.0.6 on 2026-06-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0019_classcreationsession_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcreationsession',
            name='source_page_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classcreationsession',
            name='source_type',
            field=models.CharField(choices=[('media', 'Media (audio/video)'), ('pdf', 'PDF')], db_index=True, default='media', max_length=16),
        ),
    ]
