# Generated by Django 6.0.6 on 2026-06-08 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0021_enrollment_studentunitprogress'),
        ('organizations', '0008_studygroup_studygroupteacher_studygroup_teachers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcreationsession',
            name='study_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='organizations.studygroup', verbose_name='گروه آموزشی'),
        ),
    ]
