# Generated by Django 6.0.6 on 2026-06-16 23:36
#
# Self-healing (matches organizations/0009): production may already have the
# study_group_id column from a prior deploy of the reverted org rework. Keep the
# field STATE via SeparateDatabaseAndState and add the physical column only when
# absent, so this applies on a fresh DB AND on the drifted prod DB.

import django.db.models.deletion
from django.db import migrations, models


def add_study_group_if_missing(apps, schema_editor):
    # `apps` reflects the state AFTER the preceding state-only operation, so the
    # ClassCreationSession model here already has the study_group field.
    Model = apps.get_model('classes', 'ClassCreationSession')
    table = Model._meta.db_table
    conn = schema_editor.connection
    with conn.cursor() as cursor:
        cols = {c.name for c in conn.introspection.get_table_description(cursor, table)}
    if 'study_group_id' not in cols:
        schema_editor.add_field(Model, Model._meta.get_field('study_group'))


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0022_pipeline_cancellation'),
        ('organizations', '0009_studygroup_studygroupteacher_studygroup_teachers_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='classcreationsession',
                    name='study_group',
                    field=models.ForeignKey(blank=True, help_text='گروه آموزشی (cohort) که این کلاس/آزمون متعلق به آن است.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_group_sessions', to='organizations.studygroup', verbose_name='گروه آموزشی'),
                ),
            ],
            database_operations=[],
        ),
        # State now has the field → add the physical column only if it's missing.
        migrations.RunPython(add_study_group_if_missing, noop_reverse),
    ]
