# Generated by Django 6.0.6 on 2026-06-16 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0022_pipeline_cancellation'),
        ('organizations', '0009_studygroup_studygroupteacher_studygroup_teachers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcreationsession',
            name='study_group',
            field=models.ForeignKey(blank=True, help_text='گروه آموزشی (cohort) که این کلاس/آزمون متعلق به آن است.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_group_sessions', to='organizations.studygroup', verbose_name='گروه آموزشی'),
        ),
    ]
