# Generated by Django 6.0.6 on 2026-07-04 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0023_classcreationsession_study_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('extracting', 'Extracting'), ('extracted', 'Extracted'), ('published', 'Published'), ('failed', 'Failed')], db_index=True, default='draft', max_length=16)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('allow_late', models.BooleanField(default=False)),
                ('assistant_enabled', models.BooleanField(default=True)),
                ('extract_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='classes.classcreationsession')),
            ],
        ),
        migrations.CreateModel(
            name='ClassExerciseAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image')], max_length=8)),
                ('file', models.FileField(upload_to='exercises/source/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='classes.classexercise')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClassExerciseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('assistant_enabled', models.BooleanField(default=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='classes.classexercise')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClassExerciseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('question_markdown', models.TextField()),
                ('question_type', models.CharField(choices=[('descriptive', 'Descriptive'), ('multiple_choice', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank')], default='descriptive', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('reference_answer_markdown', models.TextField(blank=True, default='')),
                ('max_points', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('grading_notes', models.TextField(blank=True, default='')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='classes.classexercisesection')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentExerciseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('grading', 'Grading'), ('graded', 'Graded'), ('grading_failed', 'Grading Failed')], db_index=True, default='submitted', max_length=16)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('score_points', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_points', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('grading_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='classes.classexercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='classexercise',
            index=models.Index(fields=['session', 'status'], name='classes_cla_session_a7c3aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='classexercisesection',
            constraint=models.UniqueConstraint(fields=('exercise', 'order'), name='uniq_exercise_section_order'),
        ),
        migrations.AddConstraint(
            model_name='classexercisequestion',
            constraint=models.UniqueConstraint(fields=('section', 'order'), name='uniq_exercise_question_order'),
        ),
        migrations.AddIndex(
            model_name='studentexercisesubmission',
            index=models.Index(fields=['exercise', 'status'], name='classes_stu_exercis_6febe5_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexercisesubmission',
            index=models.Index(fields=['student', 'status'], name='classes_stu_student_c54536_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentexercisesubmission',
            constraint=models.UniqueConstraint(fields=('exercise', 'student'), name='uniq_exercise_submission_student'),
        ),
    ]
