# Generated by Django 6.0.6 on 2026-07-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0024_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexercisesubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('grading', 'Grading'), ('graded', 'Graded'), ('grading_failed', 'Grading Failed')], db_index=True, default='submitted', max_length=16),
        ),
    ]
