# Generated by Django 6.0.6 on 2026-07-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0025_exercise_submission_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcreationsession',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
