# Generated by Django 6.0.6 on 2026-07-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0026_session_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='classexercise',
            name='intake_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='classexercise',
            name='review_ready_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classexercise',
            name='workflow_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
