# Generated by Django 6.0.2 on 2026-02-15 12:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('transcription', 'Transcription'), ('structure', 'Structure'), ('prereq_extract', 'Prerequisite Extraction'), ('prereq_teach', 'Prerequisite Teaching'), ('recap', 'Recap Generation'), ('exam_prep_structure', 'Exam Prep Structure'), ('quiz_generation', 'Quiz Generation'), ('quiz_grading', 'Quiz Grading'), ('final_exam_generation', 'Final Exam Generation'), ('hint_generation', 'Hint Generation'), ('chat_course', 'Course Chat'), ('chat_exam_prep', 'Exam Prep Chat'), ('chat_intent', 'Chat Intent Classifier'), ('chat_widget', 'Chat Widget'), ('chat_vision', 'Chat Vision'), ('memory_summary', 'Memory Summarization'), ('json_repair', 'JSON Repair'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('provider', models.CharField(default='unknown', max_length=20)),
                ('model_name', models.CharField(default='unknown', max_length=100)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('session_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('detail', models.CharField(blank=True, default='', max_length=200)),
                ('duration_ms', models.PositiveIntegerField(default=0, help_text='LLM call duration in milliseconds')),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='commons_llm_user_id_fcf86a_idx'), models.Index(fields=['feature', 'created_at'], name='commons_llm_feature_0e5334_idx'), models.Index(fields=['session_id', 'created_at'], name='commons_llm_session_f5547c_idx')],
            },
        ),
    ]
