# Generated by Django 6.0.2 on 2026-02-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_adminsetting_ticket_ticketmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmusagelog',
            name='audio_input_tokens',
            field=models.PositiveIntegerField(default=0, help_text='Audio input tokens (charged at audio rate)'),
        ),
        migrations.AddField(
            model_name='llmusagelog',
            name='cached_input_tokens',
            field=models.PositiveIntegerField(default=0, help_text='Cached input tokens (text/image/video + audio)'),
        ),
        migrations.AddField(
            model_name='llmusagelog',
            name='thinking_tokens',
            field=models.PositiveIntegerField(default=0, help_text='Thinking/reasoning tokens (charged as output)'),
        ),
    ]
