# Generated by Django 6.0.6 on 2026-06-08 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0005_alter_llmusagelog_feature'),
        ('organizations', '0009_invitationcode_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='llmusagelog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usage_logs', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='llmusagelog',
            name='study_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usage_logs', to='organizations.studygroup'),
        ),
        migrations.AddIndex(
            model_name='llmusagelog',
            index=models.Index(fields=['organization', 'created_at'], name='idx_llm_org_created'),
        ),
        migrations.AddIndex(
            model_name='llmusagelog',
            index=models.Index(fields=['study_group', 'created_at'], name='idx_llm_group_created'),
        ),
    ]
