# Generated by Codex on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0006_exercise_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmusagelog',
            name='feature',
            field=models.CharField(
                choices=[
                    ('transcription', 'Transcription'),
                    ('structure', 'Structure'),
                    ('prereq_extract', 'Prerequisite Extraction'),
                    ('prereq_teach', 'Prerequisite Teaching'),
                    ('recap', 'Recap Generation'),
                    ('exam_prep_structure', 'Exam Prep Structure'),
                    ('pdf_extraction', 'PDF Extraction (Vision)'),
                    ('quiz_generation', 'Quiz Generation'),
                    ('quiz_grading', 'Quiz Grading'),
                    ('final_exam_generation', 'Final Exam Generation'),
                    ('hint_generation', 'Hint Generation'),
                    ('chat_course', 'Course Chat'),
                    ('chat_exam_prep', 'Exam Prep Chat'),
                    ('chat_intent', 'Chat Intent Classifier'),
                    ('chat_widget', 'Chat Widget'),
                    ('chat_vision', 'Chat Vision'),
                    ('chat_system_prompt', 'Chat System Prompt'),
                    ('memory_summary', 'Memory Summarization'),
                    ('flash_cards', 'Flash Cards'),
                    ('fetch_quizzes', 'Quiz Widget'),
                    ('match_games', 'Match Game'),
                    ('practice_tests', 'Practice Test'),
                    ('meril', 'Merrill Content'),
                    ('notes_ai', 'AI Notes'),
                    ('image_plan', 'Image Plan'),
                    ('exam_prep_handwriting_vision', 'Exam Prep Handwriting Vision'),
                    ('json_repair', 'JSON Repair'),
                    ('exercise_ingest', 'Exercise Ingest (Vision/PDF)'),
                    ('exercise_structure', 'Exercise Structure'),
                    ('exercise_reference_ingest', 'Exercise Reference Ingest'),
                    ('exercise_grading', 'Exercise Grading'),
                    ('exercise_handwriting_vision', 'Exercise Handwriting Vision'),
                    ('chat_exercise', 'Exercise Assistant Chat'),
                    ('other', 'Other'),
                ],
                db_index=True,
                default='other',
                max_length=40,
            ),
        ),
    ]
