import {
  MOCK_ANALYTICS_STATS,
  MOCK_CHART_DATA,
  MOCK_DISTRIBUTION_DATA,
  MOCK_RECENT_ACTIVITIES,
  MOCK_STUDENTS,
  MOCK_COURSES,
  MOCK_MESSAGE_RECIPIENTS,
  MOCK_ADMIN_PROFILE,
  MOCK_ADMIN_SECURITY,
  MOCK_ADMIN_NOTIFICATIONS,
  MOCK_CLASS_DETAILS,
} from '@/constants/mock';

export const TEACHER_ANALYTICS_STATS = MOCK_ANALYTICS_STATS;
export const TEACHER_CHART_DATA = MOCK_CHART_DATA;
export const TEACHER_DISTRIBUTION_DATA = MOCK_DISTRIBUTION_DATA;
export const TEACHER_RECENT_ACTIVITIES = MOCK_RECENT_ACTIVITIES;
export const TEACHER_STUDENTS = MOCK_STUDENTS;
export const TEACHER_COURSES = MOCK_COURSES;
export const TEACHER_MESSAGE_RECIPIENTS = MOCK_MESSAGE_RECIPIENTS;
export const TEACHER_PROFILE_SETTINGS = {
  ...MOCK_ADMIN_PROFILE,
  name: 'معلم نمونه',
  email: 'teacher@example.com',
};
export const TEACHER_SECURITY_SETTINGS = { ...MOCK_ADMIN_SECURITY };
export const TEACHER_NOTIFICATION_SETTINGS = { ...MOCK_ADMIN_NOTIFICATIONS };
export const TEACHER_CLASS_DETAILS = { ...MOCK_CLASS_DETAILS };
