# Generated by Django 6.0.6 on 2026-08-19 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0011_alter_orgmembership_org_role_advisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نامی که مشاور و دانش\u200cآموز می\u200cبینند (مثلا ریاضی ۱)', max_length=128, verbose_name='نام درس')),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=128, verbose_name='کلید یکتاسازی')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='غیرفعال\u200cکردن، درس را از انتخاب\u200cهای جدید حذف می\u200cکند ولی تاریخ را نگه می\u200cدارد.', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('organization', models.ForeignKey(blank=True, help_text='خالی بگذارید تا این درس برای همه\u200cی مشاوران سراسری باشد.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advisory_subjects', to='organizations.organization', verbose_name='سازمان')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'درس\u200cها',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('normalized_name', 'organization'), name='uniq_advisory_subject_norm_org', violation_error_message='این درس در همین سازمان از قبل ثبت شده است.'), models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('normalized_name',), name='uniq_advisory_subject_norm_global', violation_error_message='این درس در فهرست سراسری از قبل ثبت شده است.')],
            },
        ),
    ]
