# Generated by Django 6.0.6 on 2026-08-19 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0001_initial'),
        ('organizations', '0011_alter_orgmembership_org_role_advisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_phone', models.CharField(blank=True, default='', max_length=15, verbose_name='شماره\u200cی دعوت\u200cشده')),
                ('mode', models.CharField(choices=[('freelance', 'فریلنسر'), ('org', 'سازمانی')], default='freelance', max_length=10, verbose_name='نوع همکاری')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار پذیرش'), ('ACTIVE', 'فعال'), ('REJECTED', 'رد شده'), ('ENDED', 'پایان\u200cیافته')], default='PENDING', max_length=10, verbose_name='وضعیت')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان دعوت')),
                ('invite_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='انقضای دعوت')),
                ('started_on', models.DateField(blank=True, null=True, verbose_name='شروع همکاری')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پذیرش شرایط')),
                ('advisor', models.ForeignKey(limit_choices_to={'role': 'ADVISOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='advisory_engagements', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advisory_engagements', to='organizations.organization', verbose_name='سازمان')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisory_engagements_as_student', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'همکاری مشاوره',
                'verbose_name_plural': 'همکاری\u200cهای مشاوره',
                'ordering': ['-invited_at'],
                'indexes': [models.Index(fields=['advisor', 'status'], name='idx_adv_eng_advisor_status'), models.Index(fields=['student', 'status'], name='idx_adv_eng_student_status'), models.Index(fields=['status', 'invite_expires_at'], name='idx_adv_eng_status_expires')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('mode', 'freelance'), ('organization__isnull', True)), models.Q(('mode', 'org'), ('organization__isnull', False)), _connector='OR'), name='ck_advisory_engagement_mode_org', violation_error_message='همکاری سازمانی باید سازمان داشته باشد و فریلنسری نباید.'), models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('student',), name='uniq_active_advisory_per_student', violation_error_message='این دانش\u200cآموز از قبل مشاور فعال دارد.'), models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('advisor', 'student'), name='uniq_pending_advisory_invite', violation_error_message='دعوت\u200cنامه\u200cی باز برای این دانش\u200cآموز از قبل وجود دارد.')],
            },
        ),
    ]
