# Generated by Django 6.0.6 on 2026-08-20 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0002_advisoryengagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.CharField(blank=True, choices=[('10', 'دهم'), ('11', 'یازدهم'), ('12', 'دوازدهم')], db_index=True, help_text='اختیاری؛ خالی یعنی «همه\u200cی پایه\u200cها». فقط یک فیلترِ راحتی است، نه بخشی از هویتِ درس.', max_length=2, null=True, verbose_name='پایه\u200cی تحصیلی'),
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='غیرفعال یعنی از انتخاب فعلی حذف شده؛ تاریخ نگه داشته می\u200cشود.', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_selections', to='advisory.advisoryengagement', verbose_name='همکاری')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='advisory.subject', verbose_name='درس')),
            ],
            options={
                'verbose_name': 'درسِ دانش\u200cآموز',
                'verbose_name_plural': 'درس\u200cهای دانش\u200cآموز',
                'ordering': ['subject__name'],
                'indexes': [models.Index(fields=['engagement', 'is_active'], name='idx_adv_studsub_eng_active')],
                'constraints': [models.UniqueConstraint(fields=('engagement', 'subject'), name='uniq_advisory_student_subject', violation_error_message='این درس برای این دانش\u200cآموز از قبل ثبت شده است.')],
            },
        ),
    ]
