# Generated by Django 6.0.6 on 2026-08-20 21:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0003_subject_grade_studentsubject'),
        ('organizations', '0011_alter_orgmembership_org_role_advisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subject',
            name='uniq_advisory_subject_norm_org',
        ),
        migrations.RemoveConstraint(
            model_name='subject',
            name='uniq_advisory_subject_norm_global',
        ),
        migrations.AddField(
            model_name='subject',
            name='major',
            field=models.CharField(blank=True, choices=[('math', 'ریاضی فیزیک'), ('science', 'علوم تجربی'), ('humanities', 'علوم انسانی')], db_index=True, help_text='بخشی از هویتِ درس؛ خالی یعنی درسِ عمومیِ مشترک بینِ همه\u200cی رشته\u200cهای این پایه.', max_length=20, null=True, verbose_name='رشته\u200cی تحصیلی'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.CharField(blank=True, choices=[('10', 'دهم'), ('11', 'یازدهم'), ('12', 'دوازدهم')], db_index=True, help_text='بخشی از هویتِ درس؛ خالی یعنی این درس برای هیچ دانش\u200cآموزی مشتق نمی\u200cشود.', max_length=2, null=True, verbose_name='پایه\u200cی تحصیلی'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('normalized_name', 'grade', 'major', 'organization'), name='uniq_advisory_subject_identity', nulls_distinct=False, violation_error_message='این درس با همین پایه و رشته از قبل ثبت شده است.'),
        ),
    ]
