# Generated by Django 6.0.6 on 2026-08-22 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0004_remove_subject_uniq_advisory_subject_norm_org_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(help_text='روزی که این گزارش برای آن است (میلادی؛ نمایش شمسی در فرانت\u200cاند).', verbose_name='تاریخ')),
                ('mood', models.PositiveSmallIntegerField(blank=True, help_text='عددی از ۱ تا ۵. خالی یعنی دانش\u200cآموز ثبت نکرده — که با «۱» یکی نیست.', null=True, verbose_name='حال و حوصله')),
                ('note', models.TextField(blank=True, default='', help_text='یادداشت آزاد دانش\u200cآموز برای آن روز.', verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='advisory.advisoryengagement', verbose_name='همکاری')),
            ],
            options={
                'verbose_name': 'گزارش روزانه',
                'verbose_name_plural': 'گزارش\u200cهای روزانه',
                'ordering': ['-log_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_minutes', models.PositiveIntegerField(help_text='دقیقه\u200cی واقعیِ مطالعه\u200cی این درس در آن روز.', verbose_name='دقیقه\u200cی مطالعه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='advisory.dailylog', verbose_name='گزارش روزانه')),
                ('student_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_items', to='advisory.studentsubject', verbose_name='درسِ دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'دقیقه\u200cی درس',
                'verbose_name_plural': 'دقیقه\u200cهای درس',
                'ordering': ['student_subject__subject__name'],
            },
        ),
        migrations.AddIndex(
            model_name='dailylog',
            index=models.Index(fields=['engagement', '-log_date'], name='idx_adv_log_eng_date'),
        ),
        migrations.AddConstraint(
            model_name='dailylog',
            constraint=models.UniqueConstraint(fields=('engagement', 'log_date'), name='uniq_advisory_daily_log', violation_error_message='برای این روز از قبل گزارشی ثبت شده است.'),
        ),
        migrations.AddConstraint(
            model_name='dailylog',
            constraint=models.CheckConstraint(condition=models.Q(('mood__isnull', True), models.Q(('mood__gte', 1), ('mood__lte', 5)), _connector='OR'), name='ck_advisory_log_mood_range', violation_error_message='حال و حوصله باید عددی بین ۱ تا ۵ باشد.'),
        ),
        migrations.AddConstraint(
            model_name='dailylogitem',
            constraint=models.UniqueConstraint(fields=('log', 'student_subject'), name='uniq_advisory_daily_log_item', violation_error_message='برای این درس در این روز از قبل دقیقه ثبت شده است.'),
        ),
        migrations.AddConstraint(
            model_name='dailylogitem',
            constraint=models.CheckConstraint(condition=models.Q(('actual_minutes__gt', 0), ('actual_minutes__lte', 960)), name='ck_advisory_log_item_minutes', violation_error_message='دقیقه\u200cی مطالعه باید بین ۱ تا ۹۶۰ باشد.'),
        ),
    ]
