# Generated by Django 6.0.6 on 2026-08-23 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0005_dailylog_dailylogitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='آزاد؛ نباید پیش از شروع همکاری باشد (قاعده\u200cی C3 برای نوشتن).', verbose_name='تاریخ شروع')),
                ('duration_days', models.PositiveSmallIntegerField(help_text='بین ۱ و ۹۰ روز؛ چیپ\u200cهای ۷/۱۴/۳۰ فقط میان\u200cبرهای همین عددند.', verbose_name='طول برنامه (روز)')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('PUBLISHED', 'منتشرشده')], db_index=True, default='DRAFT', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_plans', to='advisory.advisoryengagement', verbose_name='همکاری')),
            ],
            options={
                'verbose_name': 'برنامه\u200cی مطالعه',
                'verbose_name_plural': 'برنامه\u200cهای مطالعه',
                'ordering': ['start_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_offset', models.SmallIntegerField(help_text='۰ یعنی همان روزِ شروع؛ باید کمتر از طول برنامه باشد.', verbose_name='روزِ برنامه (صفر-مبنا)')),
                ('planned_minutes', models.PositiveSmallIntegerField(help_text='هم\u200cمقیاس با دقیقه\u200cی واقعیِ گزارش روزانه، تا نسبتِ تعهد معنا داشته باشد.', verbose_name='دقیقه\u200cی برنامه\u200cریزی\u200cشده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='advisory.studyplan', verbose_name='برنامه')),
                ('student_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='advisory.studentsubject', verbose_name='درسِ دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'ردیف برنامه',
                'verbose_name_plural': 'ردیف\u200cهای برنامه',
                'ordering': ['day_offset', 'student_subject__subject__name'],
            },
        ),
        migrations.CreateModel(
            name='AdvisoryAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="مثلاً 'study_feed_view' — باز کردن فید مطالعه توسط مشاور.", max_length=32, verbose_name='کنش')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_logs', to='advisory.advisoryengagement', verbose_name='همکاری')),
                ('reader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='خواننده')),
            ],
            options={
                'verbose_name': 'ثبت دسترسی',
                'verbose_name_plural': 'ثبت\u200cهای دسترسی',
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['engagement', '-accessed_at'], name='idx_adv_accesslog_eng_time'), models.Index(fields=['reader', '-accessed_at'], name='idx_adv_accesslog_reader_time')],
            },
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['engagement', 'status', 'start_date'], name='idx_adv_plan_eng_status_start'),
        ),
        migrations.AddConstraint(
            model_name='studyplan',
            constraint=models.CheckConstraint(condition=models.Q(('duration_days__gte', 1), ('duration_days__lte', 90)), name='ck_advisory_study_plan_duration', violation_error_message='طول برنامه باید بین ۱ و ۹۰ روز باشد.'),
        ),
        migrations.AddConstraint(
            model_name='studyplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'DRAFT')), fields=('engagement',), name='uniq_advisory_study_plan_draft_slot', violation_error_message='برای این همکاری از قبل یک پیش\u200cنویس وجود دارد.'),
        ),
        migrations.AddConstraint(
            model_name='studyplanitem',
            constraint=models.UniqueConstraint(fields=('plan', 'day_offset', 'student_subject'), name='uniq_advisory_plan_item_row', violation_error_message='برای هر روز و درس فقط یک ردیف بفرستید.'),
        ),
        migrations.AddConstraint(
            model_name='studyplanitem',
            constraint=models.CheckConstraint(condition=models.Q(('day_offset__gte', 0), ('day_offset__lte', 89)), name='ck_advisory_plan_item_day_offset', violation_error_message='روزِ برنامه باید بین ۰ و ۸۹ باشد.'),
        ),
        migrations.AddConstraint(
            model_name='studyplanitem',
            constraint=models.CheckConstraint(condition=models.Q(('planned_minutes__gte', 1), ('planned_minutes__lte', 960)), name='ck_advisory_plan_item_minutes', violation_error_message='دقیقه\u200cی برنامه\u200cریزی\u200cشده باید بین ۱ تا ۹۶۰ باشد.'),
        ),
    ]
