# Generated by Django 6.0.6 on 2026-08-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0006_studyplan_studyplanitem_advisoryaccesslog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.CharField(blank=True, choices=[('01', 'پایه اول'), ('02', 'پایه دوم'), ('03', 'پایه سوم'), ('04', 'پایه چهارم'), ('05', 'پایه پنجم'), ('06', 'پایه ششم'), ('07', 'هفتم'), ('08', 'هشتم'), ('09', 'نهم'), ('10', 'دهم'), ('11', 'یازدهم'), ('12', 'دوازدهم')], db_index=True, help_text='بخشی از هویتِ درس؛ خالی یعنی این درس برای هیچ دانش\u200cآموزی مشتق نمی\u200cشود.', max_length=2, null=True, verbose_name='پایه\u200cی تحصیلی'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='major',
            field=models.CharField(blank=True, choices=[('math', 'ریاضی فیزیک'), ('science', 'علوم تجربی'), ('humanities', 'علوم انسانی'), ('theology', 'علوم و معارف اسلامی'), ('technical', 'فنی و حرفه\u200cای و کاردانش')], db_index=True, help_text='بخشی از هویتِ درس؛ خالی یعنی درسِ عمومیِ مشترک بینِ همه\u200cی رشته\u200cهای این پایه.', max_length=20, null=True, verbose_name='رشته\u200cی تحصیلی'),
        ),
    ]
