# Generated by Django 6.0.6 on 2026-08-25 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0007_alter_subject_grade_alter_subject_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='day_goal',
            field=models.CharField(blank=True, default='', help_text='هدف\u200cگذاری دانش\u200cآموز برای امروز.', max_length=200, verbose_name='هدف روز'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='motivation_note',
            field=models.CharField(blank=True, default='', help_text='شعار یا جمله انگیزشی که دانش\u200cآموز برای امروز نوشته است.', max_length=200, verbose_name='جمله انگیزشی'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='test_percent',
            field=models.PositiveSmallIntegerField(blank=True, help_text='درصد آزمون امروز؛ خالی یعنی ثبت نشده — که با «۰» یکی نیست.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد آزمون'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='tests_taken',
            field=models.PositiveIntegerField(default=0, help_text='تعداد تست\u200cهایی که امروز زده شده است.', verbose_name='تعداد تست'),
        ),
    ]
