# Generated by Django 6.0.6 on 2026-08-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0008_dailylog_enrichment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubject',
            name='source',
            field=models.CharField(blank=True, choices=[('TEXTBOOK', 'کتاب درسی'), ('TEACHER_BOOKLET', 'جزوه معلم'), ('VIDEO', 'فیلم'), ('KONKUR_BOOKLET', 'جزوه/دفترنامۀ کنکور'), ('OTHER', 'سایر')], help_text='منبعی که دانش\u200cآموز این درس را با آن می\u200cخواند؛ خالی یعنی ثبت نشده.', max_length=20, null=True, verbose_name='منبع مطالعه'),
        ),
    ]
