# Generated by Django 6.0.6 on 2026-08-25 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0009_studentsubject_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='day_notes',
            field=models.JSONField(blank=True, default=dict, help_text='شکل مجاز: {"<0..6>": {"school": str≤120, "exams": …, "konkurClass": …, "preReading": …}}', verbose_name='یادداشت روزها'),
        ),
        migrations.AddField(
            model_name='studyplanitem',
            name='mastery_color',
            field=models.CharField(blank=True, choices=[('RED', 'قرمز'), ('YELLOW', 'زرد'), ('GREEN', 'سبز')], max_length=6, null=True, verbose_name='رنگ تسلط'),
        ),
        migrations.AddField(
            model_name='studyplanitem',
            name='test_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='۰ تا ۴۸۰ دقیقه؛ خالی یعنی مشاور زمانی مشخص نکرده — که با «۰» یکی نیست.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(480)], verbose_name='زمان تست'),
        ),
        migrations.AddField(
            model_name='studyplanitem',
            name='topic',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='موضوع'),
        ),
        migrations.AddField(
            model_name='studyplanitem',
            name='unit_label',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='واحد'),
        ),
    ]
