# Generated by Django 6.0.6 on 2026-08-25 20:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0010_planitem_enrichment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryIntakeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, default='', max_length=120, verbose_name='مدرسه')),
                ('city', models.CharField(blank=True, default='', max_length=60, verbose_name='شهر')),
                ('last_gpa', models.DecimalField(blank=True, decimal_places=2, help_text='عددی بین ۰ تا ۲۰؛ خالی یعنی ثبت نشده.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='معدل سال گذشته')),
                ('target_major', models.CharField(blank=True, default='', max_length=120, verbose_name='رشتهٔ هدف')),
                ('target_university', models.CharField(blank=True, default='', max_length=120, verbose_name='دانشگاه هدف')),
                ('mock_exam_institute', models.CharField(blank=True, default='', max_length=120, verbose_name='مؤسسۀ آزمون آزمایشی')),
                ('free_day_minutes', models.PositiveIntegerField(blank=True, help_text='۰ تا ۱۴۴۰ دقیقه؛ خالی یعنی ثبت نشده.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)], verbose_name='میانگین مطالعۀ روز آزاد (دقیقه)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intake', to='advisory.advisoryengagement', verbose_name='همکاری')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایشگر')),
            ],
            options={
                'verbose_name': 'پروفایل شناخت',
                'verbose_name_plural': 'پروفایل\u200cهای شناخت',
            },
        ),
        migrations.CreateModel(
            name='AdvisoryIntakeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام کلاس')),
                ('teacher', models.CharField(blank=True, default='', max_length=120, verbose_name='دبیر')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], help_text='۰ = شنبه تا ۶ = جمعه.', verbose_name='روز هفته')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='ساعت پایان')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='advisory.advisoryintakeprofile', verbose_name='پروفایل شناخت')),
            ],
            options={
                'verbose_name': 'کلاس شناخت',
                'verbose_name_plural': 'کلاس\u200cهای شناخت',
                'ordering': ['order', 'id'],
            },
        ),
    ]
