# Generated by Django 6.0.6 on 2026-08-25 20:46

import apps.advisory.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0011_intake'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='شنبهٔ آغاز هفته (میلادی).', validators=[apps.advisory.models._validate_saturday_week_start], verbose_name='شروع هفته')),
                ('scores', models.JSONField(default=dict, help_text='شکل: {"<code>": 1..5} برای هر ۱۵ معیار.', verbose_name='امتیاز معیارها')),
                ('advisor_summary', models.TextField(blank=True, default='', verbose_name='جمع\u200cبندی مشاور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_assessments', to='advisory.advisoryengagement', verbose_name='همکاری')),
            ],
            options={
                'verbose_name': 'ارزیابی هفتگی',
                'verbose_name_plural': 'ارزیابی\u200cهای هفتگی',
                'ordering': ['-week_start'],
                'constraints': [models.UniqueConstraint(fields=('engagement', 'week_start'), name='uniq_advisory_weekly_assessment', violation_error_message='برای این هفته از قبل ارزیابی ثبت شده است.')],
            },
        ),
    ]
