# Generated by Django 6.0.6 on 2026-08-25 20:47

import apps.advisory.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0012_weekly_assessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='شنبهٔ آغاز هفته (میلادی).', validators=[apps.advisory.models._validate_saturday_week_start], verbose_name='شروع هفته')),
                ('done', models.BooleanField(default=False, verbose_name='انجام شد')),
                ('call_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تماس')),
                ('topic', models.CharField(blank=True, default='', max_length=200, verbose_name='موضوع')),
                ('note', models.TextField(blank=True, default='', verbose_name='یادداشت')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='advisory.advisoryengagement', verbose_name='همکاری')),
            ],
            options={
                'verbose_name': 'تماس هفتگی',
                'verbose_name_plural': 'تماس\u200cهای هفتگی',
                'ordering': ['-week_start'],
                'constraints': [models.UniqueConstraint(fields=('engagement', 'week_start'), name='uniq_advisory_weekly_call_log', violation_error_message='برای این هفته از قبل تماسی ثبت شده است.')],
            },
        ),
    ]
