# Generated by Django 6.0.6 on 2026-08-25 22:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0013_call_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyExamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='نام آزادِ آزمون یا درس، همان\u200cطور که مشاور می\u200cنویسد.', max_length=120, verbose_name='عنوان آزمون')),
                ('exam_kind', models.CharField(choices=[('SCHOOL', 'مدرسه'), ('PERSONAL', 'شخصی'), ('CLASS_C', 'کلاس'), ('ONLINE', 'آنلاین'), ('NATIONAL', 'کنکور کشوری'), ('ADVISOR', 'آزمون مشاور')], max_length=10, verbose_name='نوع آزمون')),
                ('exam_date', models.DateField(help_text='میلادی؛ نمایش شمسی در فرانت\u200cاند.', verbose_name='تاریخ آزمون')),
                ('score_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد')),
                ('tara', models.IntegerField(blank=True, null=True, verbose_name='تراز کل')),
                ('advisor_rating', models.CharField(blank=True, choices=[('EXCELLENT', 'عالی'), ('GOOD', 'خوب'), ('FAIR', 'متوسط'), ('WEAK', 'ضعیف')], max_length=10, null=True, verbose_name='ارزیابی مشاور')),
                ('advisor_note', models.TextField(blank=True, default='', verbose_name='یادداشت مشاور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_scores', to='advisory.advisoryengagement', verbose_name='همکاری')),
                ('subject', models.ForeignKey(blank=True, help_text='پیوند اختیاری به کاتالوگ درس؛ خالی یعنی بدون پیوند.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='advisory.subject', verbose_name='درس')),
            ],
            options={
                'verbose_name': 'نمرۀ آزمون',
                'verbose_name_plural': 'نمرات آزمون',
                'ordering': ['-exam_date', '-id'],
                'indexes': [models.Index(fields=['engagement', '-exam_date'], name='idx_adv_examscore_eng_date')],
            },
        ),
    ]
