# Generated by Django 6.0.6 on 2026-08-25 22:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0014_exam_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyExamAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='شمارهٔ آزمون')),
                ('exam_date', models.DateField(blank=True, help_text='میلادی؛ نمایش شمسی در فرانت\u200cاند.', null=True, verbose_name='تاریخ آزمون')),
                ('grade_band', models.CharField(blank=True, choices=[('G10', 'دهم'), ('G11', 'یازدهم'), ('G12S1', 'دوازدهم نیمسال اول'), ('G12S2', 'دوازدهم نیمسال دوم')], max_length=10, null=True, verbose_name='بازهٔ پایه')),
                ('total_tara', models.IntegerField(blank=True, null=True, verbose_name='تراز کل')),
                ('national_rank', models.IntegerField(blank=True, null=True, verbose_name='رتبهٔ کشوری')),
                ('region_rank', models.IntegerField(blank=True, null=True, verbose_name='رتبهٔ منطقه')),
                ('city_rank', models.IntegerField(blank=True, null=True, verbose_name='رتبهٔ شهر')),
                ('highest_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='بالاترین درصد')),
                ('lowest_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='پایین\u200cترین درصد')),
                ('tara_delta', models.SmallIntegerField(blank=True, null=True, verbose_name='تغییر تراز')),
                ('advisor_report', models.TextField(blank=True, default='', verbose_name='گزارش مشاور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_analyses', to='advisory.advisoryengagement', verbose_name='همکاری')),
            ],
            options={
                'verbose_name': 'تحلیل آزمون',
                'verbose_name_plural': 'تحلیل\u200cهای آزمون',
                'ordering': ['-exam_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StudyExamAnalysisRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=120, verbose_name='نام درس')),
                ('wrong_count', models.PositiveIntegerField(default=0, verbose_name='غلط')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='نزده')),
                ('doubtful_total', models.PositiveIntegerField(default=0, verbose_name='شک\u200cدار کل')),
                ('doubtful_wrong', models.PositiveIntegerField(default=0, verbose_name='شک\u200cدار غلط')),
                ('doubtful_skipped', models.PositiveIntegerField(default=0, verbose_name='شک\u200cدار نزده')),
                ('doubtful_correct', models.PositiveIntegerField(default=0, verbose_name='شک\u200cدار درست')),
                ('cause_note', models.CharField(blank=True, default='', max_length=300, verbose_name='علت')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='advisory.studyexamanalysis', verbose_name='تحلیل')),
            ],
            options={
                'verbose_name': 'ردیف تحلیل درس',
                'verbose_name_plural': 'ردیف\u200cهای تحلیل',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StudyExamAnalysisNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='شمارهٔ سؤال')),
                ('subject_name', models.CharField(max_length=120, verbose_name='نام درس')),
                ('note', models.TextField(blank=True, default='', verbose_name='یادداشت')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='advisory.studyexamanalysis', verbose_name='تحلیل')),
            ],
            options={
                'verbose_name': 'یادداشت سؤال',
                'verbose_name_plural': 'یادداشت\u200cهای سؤال',
                'ordering': ['question_number'],
                'constraints': [models.UniqueConstraint(fields=('analysis', 'question_number'), name='uniq_advisory_analysis_note_question', violation_error_message='برای هر سؤال فقط یک یادداشت بفرستید.')],
            },
        ),
    ]
