# Generated by Django 6.0.6 on 2026-08-25 23:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0015_exam_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyOutlook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_start', models.DateField(help_text='اولین روزِ میلادیِ ماه جلالی موردنظر؛ کلیدِ یکتا به\u200cازای همکاری.', verbose_name='شروع ماه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_outlooks', to='advisory.advisoryengagement', verbose_name='همکاری')),
            ],
            options={
                'verbose_name': 'برنامهٔ ماه',
                'verbose_name_plural': 'برنامه\u200cهای ماه',
                'ordering': ['-month_start'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyOutlookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='میلادی؛ لزوماً داخل همان ماه نیست (تقویم مرزی مجاز است).', verbose_name='تاریخ')),
                ('event', models.CharField(blank=True, default='', max_length=120, verbose_name='مناسبت')),
                ('academic_note', models.CharField(blank=True, default='', max_length=200, verbose_name='تقویم تحصیلی')),
                ('tasks', models.TextField(blank=True, default='', verbose_name='کارها')),
                ('outlook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='advisory.monthlyoutlook', verbose_name='برنامهٔ ماه')),
            ],
            options={
                'verbose_name': 'ردیف روزِ ماه',
                'verbose_name_plural': 'ردیف\u200cهای روزِ ماه',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(help_text='بین ۱ تا ۱۰؛ ترتیب نمایش اسلات\u200cها در صفحه.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='پوزیشن')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('executor', models.CharField(choices=[('ADVISOR', 'مشاور'), ('STUDENT', 'دانش\u200cآموز')], max_length=10, verbose_name='مجری')),
                ('body', models.TextField(blank=True, default='', verbose_name='شرح')),
                ('outlook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='advisory.monthlyoutlook', verbose_name='برنامهٔ ماه')),
            ],
            options={
                'verbose_name': 'استراتژی ماه',
                'verbose_name_plural': 'استراتژی\u200cهای ماه',
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='monthlyoutlook',
            constraint=models.UniqueConstraint(fields=('engagement', 'month_start'), name='uniq_advisory_monthly_outlook', violation_error_message='برای این ماه از قبل برنامه\u200cای ثبت شده است.'),
        ),
        migrations.AddConstraint(
            model_name='monthlyoutlookentry',
            constraint=models.UniqueConstraint(fields=('outlook', 'date'), name='uniq_advisory_monthly_entry', violation_error_message='برای هر روز فقط یک ردیف بفرستید.'),
        ),
        migrations.AddConstraint(
            model_name='monthlystrategy',
            constraint=models.UniqueConstraint(fields=('outlook', 'position'), name='uniq_advisory_monthly_strategy', violation_error_message='برای هر پوزیشن فقط یک استراتژی مجاز است.'),
        ),
    ]
