# Generated by Django 6.0.6 on 2026-08-25 23:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0016_monthly_outlook'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان چالش')),
                ('goal_text', models.TextField(blank=True, default='', verbose_name='تعریف و هدف')),
                ('daily_routine', models.CharField(blank=True, default='', max_length=200, verbose_name='روتین روزانه')),
                ('execution_note', models.CharField(blank=True, default='', max_length=200, verbose_name='نوع اجرا')),
                ('observer', models.CharField(blank=True, default='', max_length=120, verbose_name='مجری و ناظر')),
                ('problem_target', models.TextField(blank=True, default='', verbose_name='مشکل و نتیجهٔ مدنظر')),
                ('start_date', models.DateField(help_text='میلادی؛ پایان همیشه ششمین روز بعد است.', verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(editable=False, help_text='ششمین روز پس از شروع؛ توسط سرور محاسبه می\u200cشود.', verbose_name='تاریخ پایان')),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('DONE', 'پایان\u200cیافته'), ('CANCELLED', 'لغوشده')], db_index=True, default='ACTIVE', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='advisory.advisoryengagement', verbose_name='همکاری')),
            ],
            options={
                'verbose_name': 'چالش هفت\u200cروزه',
                'verbose_name_plural': 'چالش\u200cهای هفت\u200cروزه',
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StudyChallengeDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField(help_text='بین ۱ تا ۷.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='شمارهٔ روز')),
                ('goal', models.CharField(blank=True, default='', max_length=200, verbose_name='هدف\u200cگذاری روز')),
                ('summary', models.TextField(blank=True, default='', verbose_name='خلاصۀ کارها/مشکلات/نتیجه')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='advisory.studychallenge', verbose_name='چالش')),
            ],
            options={
                'verbose_name': 'روزِ چالش',
                'verbose_name_plural': 'روزهای چالش',
                'ordering': ['day_number'],
            },
        ),
        migrations.AddIndex(
            model_name='studychallenge',
            index=models.Index(fields=['engagement', 'status'], name='idx_adv_challenge_eng_status'),
        ),
        migrations.AddConstraint(
            model_name='studychallenge',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='ck_advisory_challenge_dates', violation_error_message='تاریخ پایان باید بعد از تاریخ شروع باشد.'),
        ),
        migrations.AddConstraint(
            model_name='studychallengeday',
            constraint=models.UniqueConstraint(fields=('challenge', 'day_number'), name='uniq_advisory_challenge_day', violation_error_message='برای هر روز فقط یک ردیف بفرستید.'),
        ),
    ]
