# Generated by Django 6.0.6 on 2026-08-26 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0017_challenge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryStudentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='نام پوشه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisory_folders', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
            ],
            options={
                'verbose_name': 'پوشهٔ دانش\u200cآموزان',
                'verbose_name_plural': 'پوشه\u200cهای دانش\u200cآموزان',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='advisoryengagement',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements', to='advisory.advisorystudentfolder', verbose_name='پوشه'),
        ),
        migrations.AddConstraint(
            model_name='advisorystudentfolder',
            constraint=models.UniqueConstraint(fields=('advisor', 'name'), name='uniq_advisory_student_folder', violation_error_message='پوشه\u200cای با این نام دارید.'),
        ),
    ]
