# Generated by Django 6.0.6 on 2026-08-30 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0018_student_folders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylogitem',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('LESSON', 'درسنامه'), ('EDU_TEST', 'تست آموزشی'), ('TIMED_TEST', 'تست زمان\u200cدار'), ('REVIEW', 'مرور'), ('SUMMARY', 'خلاصه\u200cنویسی')], default='', max_length=12, verbose_name='نوع مطالعه'),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='phase',
            field=models.CharField(blank=True, choices=[('BASE', 'پایه\u200cسازی'), ('TEST', 'تست\u200cزنی'), ('REVIEW', 'جمع\u200cبندی'), ('FINAL', 'هفته\u200cهای آخر')], default='', max_length=10, verbose_name='فاز برنامه'),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='strategy',
            field=models.CharField(blank=True, choices=[('VOLUME', 'حجمی'), ('TIME', 'زمانی'), ('HYBRID', 'حجمی-زمانی')], default='', max_length=10, verbose_name='استراتژی برنامه'),
        ),
        migrations.AddField(
            model_name='studyplanitem',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ساعت شروع'),
        ),
        migrations.CreateModel(
            name='AdvisoryGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_title', models.CharField(help_text='مثل: پزشکی، دانشگاه شهید بهشتی', max_length=120, verbose_name='هدف')),
                ('target_rank', models.CharField(blank=True, default='', max_length=60, verbose_name='رتبه/تراز هدف')),
                ('current_rank', models.CharField(blank=True, default='', max_length=60, verbose_name='رتبه/تراز فعلی')),
                ('note', models.TextField(blank=True, default='', verbose_name='یادداشت مسیر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='advisory.advisoryengagement', verbose_name='همکاری')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisory_goals_written', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش\u200cگر')),
            ],
            options={
                'verbose_name': 'هدف تحصیلی',
                'verbose_name_plural': 'اهداف تحصیلی',
            },
        ),
        migrations.CreateModel(
            name='MistakeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='مبحث')),
                ('status', models.CharField(choices=[('WRONG', 'غلط'), ('DOUBT_RIGHT', 'درست اما شک\u200cدار'), ('UNANSWERED', 'نزده')], default='WRONG', max_length=12, verbose_name='وضعیت پاسخ')),
                ('error_type', models.CharField(choices=[('CONCEPT', 'مفهومی'), ('FORGET', 'فراموشی'), ('METHOD', 'تشخیص روش'), ('EXECUTION', 'محاسباتی/اجرایی'), ('READING', 'خواندن سؤال'), ('TIME', 'مدیریت زمان')], max_length=12, verbose_name='نوع خطا')),
                ('cause', models.CharField(blank=True, default='', max_length=300, verbose_name='علت اصلی')),
                ('fix_note', models.CharField(blank=True, default='', max_length=300, verbose_name='نکتهٔ اصلاحی')),
                ('next_action', models.CharField(blank=True, default='', max_length=300, verbose_name='اقدام بعدی')),
                ('priority', models.CharField(choices=[('HIGH', 'بالا'), ('MEDIUM', 'متوسط'), ('LOW', 'کم')], default='MEDIUM', max_length=8, verbose_name='اولویت')),
                ('source_ref', models.CharField(blank=True, default='', max_length=120, verbose_name='منبع/شماره سؤال')),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='تاریخ مرور')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='رفع شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='advisory.advisoryengagement', verbose_name='همکاری')),
                ('student_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mistake_entries', to='advisory.studentsubject', verbose_name='درسِ دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'خطای دفتر اشتباهات',
                'verbose_name_plural': 'ردیف\u200cهای دفتر اشتباهات',
                'ordering': ['is_resolved', '-created_at'],
                'indexes': [models.Index(fields=['engagement', 'is_resolved', '-created_at'], name='idx_adv_mistakes_eng_open')],
            },
        ),
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='مبحث')),
                ('status', models.CharField(choices=[('NEW', 'شروع\u200cنشده'), ('STUDIED', 'خوانده\u200cشده'), ('NEEDS_REVIEW', 'نیاز به مرور'), ('MASTERED', 'تسلط\u200cیافته')], default='NEW', max_length=14, verbose_name='وضعیت')),
                ('next_review_at', models.DateField(blank=True, null=True, verbose_name='مرور بعدی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to='advisory.advisoryengagement', verbose_name='همکاری')),
                ('student_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topic_progress', to='advisory.studentsubject', verbose_name='درسِ دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'پیشرفت مبحث',
                'verbose_name_plural': 'پیشرفت مباحث',
                'ordering': ['student_subject__subject__name', 'topic'],
                'constraints': [models.UniqueConstraint(fields=('engagement', 'student_subject', 'topic'), name='uniq_advisory_topic_progress', violation_error_message='این مبحث از قبل در فهرست هست.')],
            },
        ),
    ]
