# Wave 5 (2026-08-31): the ParentLink table — one parent phone invited to read
# one engagement's weekly digest. PENDING until the phone's owner verifies an
# OTP, ACTIVE while the digest is readable, REVOKED as kept-for-audit history.
# Authored by makemigrations; only this header is hand-written.

# Generated by Django 6.0.6 on 2026-08-31 12:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0019_dailylogitem_activity_type_studyplan_phase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, help_text='۰۹ + ۹ رقم؛ کلید اتصال هنگام ورود والد.', max_length=11, validators=[django.core.validators.RegexValidator('^09\\d{9}$', message='شمارهٔ والد باید ۰۹ + ۹ رقم باشد.')], verbose_name='شمارهٔ والد')),
                ('relation', models.CharField(choices=[('father', 'پدر'), ('mother', 'مادر'), ('guardian', 'سرپرست')], max_length=8, verbose_name='نسبت')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار تأیید'), ('ACTIVE', 'فعال'), ('REVOKED', 'لغوشده')], db_index=True, default='PENDING', max_length=8, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('activated_at', models.DateField(blank=True, help_text='روزی که والد با کد یکبارمصرف وارد شد.', null=True, verbose_name='تاریخ فعال\u200cسازی')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='advisory.advisoryengagement', verbose_name='همکاری')),
                ('parent', models.ForeignKey(blank=True, help_text='تا ورود با کد یکبارمصرف خالی می\u200cماند.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_links', to=settings.AUTH_USER_MODEL, verbose_name='والد')),
            ],
            options={
                'verbose_name': 'پیوند والد',
                'verbose_name_plural': 'پیوندهای والدین',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['phone', 'status'], name='idx_parent_link_phone_status'), models.Index(fields=['engagement', 'status'], name='idx_parent_link_eng_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'ACTIVE'])), fields=('engagement', 'phone'), name='uniq_active_parent_link', violation_error_message='برای این شماره پیوند والد از قبل وجود دارد.'), models.CheckConstraint(condition=models.Q(('phone__regex', '^09\\d{9}$')), name='ck_parent_link_phone_shape', violation_error_message='شمارهٔ والد باید ۰۹ + ۹ رقم باشد.')],
            },
        ),
    ]
