# Generated by Django 6.0.2 on 2026-02-21 22:28

import apps.organizations.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام مدرسه یا موسسه', max_length=255, verbose_name='عنوان سازمان')),
                ('slug', models.SlugField(help_text='نام انگلیسی برای آدرس اینترنتی (مثلا alborz-high)', max_length=128, unique=True, verbose_name='شناسه یکتا')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/', verbose_name='لوگوی سازمان')),
                ('student_capacity', models.PositiveIntegerField(default=100, help_text='سقف تعداد دانش\u200cآموزی که سازمان پولش را داده', verbose_name='ظرفیت دانش\u200cآموز')),
                ('subscription_status', models.CharField(choices=[('active', 'فعال'), ('expired', 'منقضی شده'), ('suspended', 'تعلیق شده')], db_index=True, default='active', max_length=16, verbose_name='وضعیت اشتراک')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='کاربری که مدیر کل این سازمان است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_organizations', to=settings.AUTH_USER_MODEL, verbose_name='مالک اصلی')),
            ],
            options={
                'verbose_name': 'سازمان',
                'verbose_name_plural': 'سازمان\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.organizations.models._generate_invite_code, max_length=64, unique=True, verbose_name='کد دعوت')),
                ('target_role', models.CharField(choices=[('admin', 'مدیر'), ('deputy', 'معاون'), ('teacher', 'معلم'), ('student', 'دانش\u200cآموز')], default='student', max_length=16, verbose_name='نقش هدف')),
                ('label', models.CharField(blank=True, help_text='نام توصیفی مثلا "دهم-ریاضی" یا "معلمان فیزیک"', max_length=128, verbose_name='برچسب')),
                ('max_uses', models.PositiveIntegerField(default=30, verbose_name='ظرفیت استفاده')),
                ('use_count', models.PositiveIntegerField(default=0, verbose_name='دفعات استفاده شده')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invitation_codes', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_codes', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'کد دعوت',
                'verbose_name_plural': 'کدهای دعوت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_role', models.CharField(choices=[('admin', 'مدیر'), ('deputy', 'معاون'), ('teacher', 'معلم'), ('student', 'دانش\u200cآموز')], default='student', max_length=16, verbose_name='نقش سازمانی')),
                ('internal_id', models.CharField(blank=True, help_text='شماره دانش\u200cآموزی یا کد پرسنلی معلم', max_length=64, verbose_name='شناسه داخلی')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('suspended', 'تعلیق شده')], db_index=True, default='active', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عضویت سازمانی',
                'verbose_name_plural': 'عضویت\u200cهای سازمانی',
                'ordering': ['-joined_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'organization'), name='uniq_membership_user_org')],
            },
        ),
    ]
