# Generated by Django 6.0.6 on 2026-06-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_studygroup_studygroupteacher_studygroup_teachers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationcode',
            name='phone',
            field=models.CharField(blank=True, db_index=True, help_text='اگر تنظیم شود، فقط همین شماره می\u200cتواند کد را فعال کند (مثلاً مدیر سازمان).', max_length=15, verbose_name='موبایل دعوت\u200cشونده'),
        ),
    ]
