# Generated by Django 6.0.6 on 2026-06-16 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_promote_org_admins_to_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثلاً «دهم ریاضی»', max_length=128, verbose_name='نام گروه')),
                ('grade_label', models.CharField(blank=True, help_text='مثلاً «دهم»', max_length=64, verbose_name='پایه')),
                ('subject', models.CharField(blank=True, help_text='مثلاً «ریاضی»', max_length=128, verbose_name='درس/رشته')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('archived', 'بایگانی شده')], db_index=True, default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_study_groups', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_groups', to='organizations.organization', verbose_name='سازمان')),
            ],
            options={
                'verbose_name': 'گروه آموزشی',
                'verbose_name_plural': 'گروه\u200cهای آموزشی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyGroupTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('study_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_links', to='organizations.studygroup')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_group_teacher_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تخصیص معلم به گروه',
                'verbose_name_plural': 'تخصیص معلمان به گروه\u200cها',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddField(
            model_name='studygroup',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='study_groups_taught', through='organizations.StudyGroupTeacher', through_fields=('study_group', 'teacher'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudyGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال')], db_index=True, default='active', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_group_memberships', to=settings.AUTH_USER_MODEL)),
                ('study_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_memberships', to='organizations.studygroup')),
            ],
            options={
                'verbose_name': 'عضویت در گروه آموزشی',
                'verbose_name_plural': 'عضویت\u200cهای گروه آموزشی',
                'ordering': ['-joined_at'],
                'constraints': [models.UniqueConstraint(fields=('study_group', 'student'), name='uniq_studygroup_student')],
            },
        ),
        migrations.AddConstraint(
            model_name='studygroupteacher',
            constraint=models.UniqueConstraint(fields=('study_group', 'teacher'), name='uniq_studygroup_teacher'),
        ),
        migrations.AddConstraint(
            model_name='studygroup',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_studygroup_org_name'),
        ),
    ]
