# Generated by Django 6.0.6 on 2026-08-29 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_impersonationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='impersonationlog',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='کاربری که ورود مستقیم را آغاز کرد.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonations_started', to=settings.AUTH_USER_MODEL, verbose_name='مدیر'),
        ),
    ]
